version: "3.8"

services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: frontend
    restart: always
    networks:
      - host
    environment:
      - NEXTAUTH_URL="http://localhost:3040"
      - NEXTAUTH_SECRET="cyytdoNtqxVc151S+vLNHSOZ6IgT3c2wp6HwLnVtHO0="

  nginx:
    build: ./nginx
    ports:
      - 3040:80
    restart: always
    depends_on:
      - frontend
    networks:
      - host

networks:
  host:
    driver: bridge
