export const documents = [
  {
    id: 1,
    name: "Requerimento de registro do candidato(a)/indicado(a) a Gestor(a)",
    alt: "Remy Sharp",
    src: "https://upload.wikimedia.org/wikipedia/commons/7/70/User_icon_BLACK-01.png",
  },
  {
    id: 2,
    name: "Ficha de qualificação do(a) candidato(a)/indicado(a)",
    alt: "Remy Sharp",
    src: "https://upload.wikimedia.org/wikipedia/commons/7/70/User_icon_BLACK-01.png",
  },
  {
    id: 3,
    name: "Cópia do título de habilitação profissional autenticada em cartório",
    alt: "Remy Sharp",
    src: "https://upload.wikimedia.org/wikipedia/commons/7/70/User_icon_BLACK-01.png",
  },
  {
    id: 4,
    name: "Cópia da Proposta de Trabalho, em consonância com o Projeto Político Pedagógico da Unidade de Ensino",
    alt: "Remy Sharp",
    src: "https://upload.wikimedia.org/wikipedia/commons/7/70/User_icon_BLACK-01.png",
  },
  {
    id: 5,
    name: "Declaração de disponibilidade para dedicação exclusiva",
    alt: "Remy Sharp",
    src: "https://upload.wikimedia.org/wikipedia/commons/7/70/User_icon_BLACK-01.png",
  },
  {
    id: 6,
    name: "Cópia do certificado do curso de Formação Continuada para Gestores, realizado no biênio 2022-2023, devidamente autenticado em cartório ou Declaração do CEFOPE comprovando a aprovação na formação",
    alt: "Remy Sharp",
    src: "https://upload.wikimedia.org/wikipedia/commons/7/70/User_icon_BLACK-01.png",
  },
  {
    id: 7,
    name: "Declaração de efetivo exercício na Rede Municipal de Ensino",
    alt: "Remy Sharp",
    src: "https://upload.wikimedia.org/wikipedia/commons/7/70/User_icon_BLACK-01.png",
  },
  {
    id: 8,
    name: "Certificado do curso de Formação Básica para candidatos/indicados a gestores para o biênio 2024/2025 oferecido pela SEMED",
    alt: "Remy Sharp",
    src: "https://upload.wikimedia.org/wikipedia/commons/7/70/User_icon_BLACK-01.png",
  },
  {
    id: 9,
    name: "Certidão Negativa Criminal e Cível Estadual",
    alt: "Remy Sharp",
    src: "https://upload.wikimedia.org/wikipedia/commons/7/70/User_icon_BLACK-01.png",
  },
  {
    id: 10,
    name: "Certidão Negativa Criminal e Cível da Justiça Federal",
    alt: "Remy Sharp",
    src: "https://upload.wikimedia.org/wikipedia/commons/7/70/User_icon_BLACK-01.png",
  },
  {
    id: 11,
    name: "Certidão Negativa Criminal da Justiça Eleitoral",
    alt: "Remy Sharp",
    src: "https://upload.wikimedia.org/wikipedia/commons/7/70/User_icon_BLACK-01.png",
  },
  {
    id: 12,
    name: "Original da Pesquisa emitida pela Câmara de Dirigentes Lojistas de Anápolis – CDL",
    alt: "Remy Sharp",
    src: "https://upload.wikimedia.org/wikipedia/commons/7/70/User_icon_BLACK-01.png",
  },
  {
    id: 13,
    name: "Declaração de não interrupção do mandato por licenças opcionais",
    alt: "Remy Sharp",
    src: "https://upload.wikimedia.org/wikipedia/commons/7/70/User_icon_BLACK-01.png",
  },
  {
    id: 14,
    name: "Declaração de tempo de docência",
    alt: "Remy Sharp",
    src: "https://upload.wikimedia.org/wikipedia/commons/7/70/User_icon_BLACK-01.png",
  },
  {
    id: 15,
    name: "Declaração de tempo de modulação na Unidade de Ensino",
    alt: "Remy Sharp",
    src: "https://upload.wikimedia.org/wikipedia/commons/7/70/User_icon_BLACK-01.png",
  },
  {
    id: 16,
    name: "Declaração de que possui apenas uma matrícula na Rede Municipal de Educação",
    alt: "Remy Sharp",
    src: "https://upload.wikimedia.org/wikipedia/commons/7/70/User_icon_BLACK-01.png",
  },
  {
    id: 17,
    name: "Declaração de nada consta",
    alt: "Remy Sharp",
    src: "https://upload.wikimedia.org/wikipedia/commons/7/70/User_icon_BLACK-01.png",
  },
  {
    id: 18,
    name: "Declaração de regularidade com o FUMMDE",
    alt: "Remy Sharp",
    src: "https://upload.wikimedia.org/wikipedia/commons/7/70/User_icon_BLACK-01.png",
  },
  {
    id: 19,
    name: "Laudo para professores readaptados expedido pela perícia médica (somente candidatos(as) ou indicados(as) readaptados(as))",
    alt: "Remy Sharp",
    src: "https://upload.wikimedia.org/wikipedia/commons/7/70/User_icon_BLACK-01.png",
  },
];
